"""Baseline schema.

Creates the full schema from the ORM metadata. This is a baseline migration: it
reflects src/models/db.py exactly (including the generated tsvector column and
its GIN index), so it stays correct as one unit. Subsequent changes should be
added as autogenerated incremental migrations on top of this revision.

Revision ID: 0001_baseline
Revises:
Create Date: 2026-09-10
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# Import the models so every table is attached to Base.metadata.
import src.models.db  # noqa: F401
from src.db.base import Base

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
