"""Render the LangGraph pipeline as a Mermaid diagram into docs/pipeline-graph.md.

Builds the StateGraph with lightweight in-memory doubles (no network, no keys),
compiles it, and writes `compiled_graph.get_graph().draw_mermaid()` into a docs
file. Run: `uv run python -m scripts.generate_graph_diagram`.
"""

from __future__ import annotations

from pathlib import Path

from src.retrieval.index import InMemoryPassageIndex
from src.stores.graph import InMemoryGraphStore
from src.workflows.nodes import Deps
from src.workflows.research import compile_graph

OUTPUT_PATH = Path("docs/pipeline-graph.md")

DOC_HEADER = """# Research pipeline graph

Auto-generated by `scripts/generate_graph_diagram.py`. The pipeline is a LangGraph
`StateGraph` over `ResearchState`: plan → search → (extract → score → verify) →
synthesize, with a conditional edge after search that skips straight to synthesis
when no passages were found.

```mermaid
"""

DOC_FOOTER = "```\n"


def _placeholder_deps() -> Deps:
    # Node bodies never run for diagram rendering; only the graph shape is read.
    return Deps(
        llm=None,  # type: ignore[arg-type]
        embeddings=None,  # type: ignore[arg-type]
        connectors={},
        passage_index=InMemoryPassageIndex(),
        graph_store=InMemoryGraphStore(),
    )


def render_mermaid() -> str:
    compiled_graph = compile_graph(_placeholder_deps())
    return compiled_graph.get_graph().draw_mermaid()


def main() -> int:
    mermaid = render_mermaid()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(DOC_HEADER + mermaid + DOC_FOOTER, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
